(() => {
const C=document.querySelector('#game'),X=C.getContext('2d'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const W=1280,H=720,keys={},mouse={x:W/2,y:H/2,down:false}; let running=false,paused=false,last=0,mode='solo',wave=0,score=0,enemies=[],shots=[],particles=[],players=[],spawnLeft=0,spawnTimer=0,between=false,pc,dc,isHost=false,netTick=0;
const upgrades=[['OVERCLOCK','+25% fire rate','rate'],['HEAVY ROUNDS','+35% damage','damage'],['PHASE BOOTS','+18% move speed','speed'],['NANOFIBER','Restore health + max HP','health'],['TWIN SHOT','Fire an extra projectile','multi'],['QUICKSHIFT','Dash recharges faster','dash']];
function player(x,color,id){return{x,y:H/2,vx:0,vy:0,angle:0,hp:100,maxHp:100,color,id,speed:250,damage:22,rate:.18,cool:0,dash:0,multi:1,remote:false}}
function show(id){['menu','lobby','upgrade','gameover'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));}
function start(m){mode=m;wave=0;score=0;enemies=[];shots=[];particles=[];players=[player(W*.35,'#68f7c2',0)];if(m==='local')players.push(player(W*.65,'#54bfff',1));if(m==='online'){players.push(player(W*.65,'#54bfff',1));players[1].remote=true}show('none');running=true;paused=false;$('#mode').textContent=m.toUpperCase();nextWave();}
function nextWave(){wave++;spawnLeft=5+wave*3;spawnTimer=.4;between=false;$('#wave').textContent=wave;}
function spawn(){let e=Math.floor(Math.random()*4),x=e%2?Math.random()*W:e?W+30:-30,y=e%2?(e===1?-30:H+30):Math.random()*H;let type=Math.random()<Math.min(.12+wave*.02,.42)?'tank':'drone';enemies.push({x,y,r:type==='tank'?22:14,hp:type==='tank'?80+wave*12:35+wave*6,max:1,speed:type==='tank'?55:90+wave*3,type,hit:0});}
function shoot(p){if(p.cool>0)return;p.cool=p.rate;for(let i=0;i<p.multi;i++){let a=p.angle+(i-(p.multi-1)/2)*.13;shots.push({x:p.x+Math.cos(a)*18,y:p.y+Math.sin(a)*18,vx:Math.cos(a)*650,vy:Math.sin(a)*650,life:1.2,dmg:p.damage,owner:p.id})}}
function burst(x,y,color,n=9){for(let i=0;i<n;i++){let a=Math.random()*7,s=Math.random()*150;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.4,color})}}
function input(p,dt){let dx=0,dy=0;if(p.id===0){dx=(keys.KeyD?1:0)-(keys.KeyA?1:0);dy=(keys.KeyS?1:0)-(keys.KeyW?1:0);p.angle=Math.atan2(mouse.y-p.y,mouse.x-p.x);if(mouse.down)shoot(p)}else if(mode==='local'){dx=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);dy=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0);let ax=(keys.Numpad6?1:0)-(keys.Numpad4?1:0),ay=(keys.Numpad2?1:0)-(keys.Numpad8?1:0);if(ax||ay){p.angle=Math.atan2(ay,ax);shoot(p)}}if(dx||dy){let l=Math.hypot(dx,dy);p.x+=dx/l*p.speed*dt;p.y+=dy/l*p.speed*dt}p.x=Math.max(18,Math.min(W-18,p.x));p.y=Math.max(18,Math.min(H-18,p.y));}
function dash(p){if(p.dash>0||p.remote)return;let dx=p.id===0?(keys.KeyD?1:0)-(keys.KeyA?1:0):(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),dy=p.id===0?(keys.KeyS?1:0)-(keys.KeyW?1:0):(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0);if(!dx&&!dy){dx=Math.cos(p.angle);dy=Math.sin(p.angle)}let l=Math.hypot(dx,dy);p.x+=dx/l*110;p.y+=dy/l*110;p.dash=1.5;burst(p.x,p.y,p.color,14)}
function update(dt){if(!running||paused||between)return;players.forEach(p=>{if(!p.remote)input(p,dt);p.cool=Math.max(0,p.cool-dt);p.dash=Math.max(0,p.dash-dt)});if(isHost||mode!=='online'){spawnTimer-=dt;if(spawnLeft&&spawnTimer<=0){spawn();spawnLeft--;spawnTimer=Math.max(.12,.7-wave*.02)}for(let e of enemies){let live=players.filter(p=>p.hp>0),t=live.sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y))[0];if(t){let a=Math.atan2(t.y-e.y,t.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(Math.hypot(t.x-e.x,t.y-e.y)<e.r+15){t.hp-=24*dt;e.hit=.08}}e.hit=Math.max(0,e.hit-dt)}for(let s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let e of enemies)if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+4){e.hp-=s.dmg;s.life=0;e.hit=.1;if(e.hp<=0){score+=e.type==='tank'?50:20;burst(e.x,e.y,e.type==='tank'?'#ffc55c':'#ff496c',14)}}}enemies=enemies.filter(e=>e.hp>0);shots=shots.filter(s=>s.life>0);if(!spawnLeft&&!enemies.length){between=true;setTimeout(showUpgrades,600)}if(players.every(p=>p.hp<=0))gameOver()}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);$('#hostiles').textContent=enemies.length+spawnLeft;$('#score').textContent=score;if(mode==='online')sync(dt)}
function showUpgrades(){if(mode==='online'&&!isHost)return;let picks=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);$('#cards').innerHTML=picks.map(u=>`<button class="upgrade-card" data-up="${u[2]}"><small>MODULE</small><b>${u[0]}</b><span>${u[1]}</span></button>`).join('');show('upgrade');$$('[data-up]').forEach(b=>b.onclick=()=>choose(b.dataset.up));}
function choose(k){players.forEach(p=>{if(k==='rate')p.rate*=.75;if(k==='damage')p.damage*=1.35;if(k==='speed')p.speed*=1.18;if(k==='health'){p.maxHp+=25;p.hp=p.maxHp}if(k==='multi')p.multi++;if(k==='dash')p.dash=Math.max(0,p.dash-.6)});if(dc?.readyState==='open')dc.send(JSON.stringify({t:'upgrade',k}));show('none');nextWave()}
function gameOver(){running=false;$('#finalScore').textContent=`Wave ${wave} • ${score.toLocaleString()} points`;show('gameover')}
function draw(){X.fillStyle='#0a1018';X.fillRect(0,0,W,H);X.strokeStyle='#172333';X.lineWidth=1;for(let x=0;x<W;x+=64){X.beginPath();X.moveTo(x,0);X.lineTo(x,H);X.stroke()}for(let y=0;y<H;y+=64){X.beginPath();X.moveTo(0,y);X.lineTo(W,y);X.stroke()}X.strokeStyle='#20364b';X.lineWidth=3;X.strokeRect(18,18,W-36,H-36);shots.forEach(s=>{X.fillStyle=s.owner?'#54bfff':'#68f7c2';X.shadowBlur=12;X.shadowColor=X.fillStyle;X.beginPath();X.arc(s.x,s.y,4,0,7);X.fill()});X.shadowBlur=0;enemies.forEach(e=>{X.save();X.translate(e.x,e.y);X.rotate(performance.now()/900);X.fillStyle=e.hit?'#fff':e.type==='tank'?'#ffc55c':'#ff496c';X.strokeStyle=X.fillStyle;X.lineWidth=3;if(e.type==='tank'){X.strokeRect(-e.r,-e.r,e.r*2,e.r*2);X.rotate(.7);X.fillRect(-9,-9,18,18)}else{X.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3;X.lineTo(Math.cos(a)*e.r,Math.sin(a)*e.r)}X.closePath();X.fill()}X.restore()});players.forEach(p=>{if(p.hp<=0)return;X.save();X.translate(p.x,p.y);X.rotate(p.angle);X.shadowBlur=20;X.shadowColor=p.color;X.strokeStyle=p.color;X.fillStyle='#0d1721';X.lineWidth=4;X.beginPath();X.arc(0,0,15,0,7);X.fill();X.stroke();X.fillStyle=p.color;X.fillRect(5,-4,23,8);X.restore();X.fillStyle='#1d2937';X.fillRect(p.x-22,p.y+25,44,5);X.fillStyle=p.hp>30?p.color:'#ff496c';X.fillRect(p.x-22,p.y+25,44*Math.max(0,p.hp/p.maxHp),5)});particles.forEach(p=>{X.globalAlpha=Math.max(0,p.life*2);X.fillStyle=p.color;X.fillRect(p.x,p.y,3,3)});X.globalAlpha=1;if(paused){X.fillStyle='#080b12aa';X.fillRect(0,0,W,H);X.fillStyle='#fff';X.font='700 42px system-ui';X.textAlign='center';X.fillText('PAUSED',W/2,H/2)}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function waitIce(p){return new Promise(r=>{if(p.iceGatheringState==='complete')r();else p.onicegatheringstatechange=()=>p.iceGatheringState==='complete'&&r()})}
function encode(d){return btoa(unescape(encodeURIComponent(JSON.stringify(d))))}function decode(s){return JSON.parse(decodeURIComponent(escape(atob(s.trim()))))}
function makePC(){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});pc.onconnectionstatechange=()=>{$('#netStatus').textContent='Link: '+pc.connectionState;if(pc.connectionState==='connected')setTimeout(()=>start('online'),500)};pc.ondatachannel=e=>wire(e.channel);return pc}
function wire(ch){dc=ch;dc.onopen=()=>$('#netStatus').textContent='Connected — launching…';dc.onmessage=e=>{let m=JSON.parse(e.data);if(m.t==='input'&&isHost){let p=players[1];Object.assign(p,m.p);if(m.fire)shoot(p)}if(m.t==='state'&&!isHost){wave=m.wave;score=m.score;enemies=m.enemies;shots=m.shots;Object.assign(players[1],m.players[0]);players[0].hp=m.players[1].hp;players[0].maxHp=m.players[1].maxHp}if(m.t==='upgrade'&&!isHost)choose(m.k)}}
function sync(dt){if(!dc||dc.readyState!=='open')return;netTick+=dt;if(netTick<1/30)return;netTick=0;if(isHost)dc.send(JSON.stringify({t:'state',wave,score,enemies,shots,players}));else{let p=players[0];dc.send(JSON.stringify({t:'input',p:{x:p.x,y:p.y,angle:p.angle,hp:p.hp},fire:mouse.down}))}}
async function host(){isHost=true;$('#rolePick').classList.add('hidden');$('#hostFlow').classList.remove('hidden');let p=makePC();wire(p.createDataChannel('game',{ordered:false,maxRetransmits:0}));await p.setLocalDescription(await p.createOffer());await waitIce(p);$('#offerOut').value=encode(p.localDescription);$('#netStatus').textContent='Offer ready'}
async function answer(){try{isHost=false;let p=makePC();await p.setRemoteDescription(decode($('#offerIn').value));await p.setLocalDescription(await p.createAnswer());await waitIce(p);$('#answerOut').value=encode(p.localDescription);$('#netStatus').textContent='Answer ready — send it to the host'}catch(e){toast('That offer code is invalid')}}
async function accept(){try{await pc.setRemoteDescription(decode($('#answerIn').value));$('#netStatus').textContent='Connecting…'}catch(e){toast('That answer code is invalid')}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),1800)}
$$('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='solo'||a==='local')start(a);if(a==='online')show('lobby');if(a==='back'){running=false;show('menu')}if(a==='host')host();if(a==='join'){$('#rolePick').classList.add('hidden');$('#joinFlow').classList.remove('hidden')}if(a==='makeAnswer')answer();if(a==='acceptAnswer')accept();if(a==='restart')start(mode)});$$('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($('#'+b.dataset.copy).value);toast('Connection code copied')});
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')dash(players[0]);if(e.code==='Enter'&&players[1])dash(players[1])});addEventListener('keyup',e=>keys[e.code]=false);C.addEventListener('mousemove',e=>{let r=C.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height});C.addEventListener('mousedown',()=>mouse.down=true);addEventListener('mouseup',()=>mouse.down=false);$('#pauseBtn').onclick=()=>paused=!paused;
})();
